### ISSUE TITLE
2+ days of "Failed to Fetch Resource" when loading steam workshop BP's

### ISSUE THREAD

**Issue by rayanth** [Akuukis/sepraisal#31]
### Summary
Unable to load anything from Steam Workshop. Receive two different errors depending on browser. 

### Steps to Reproduce actual behavior

1. Go to https://spaceengineerspraisal.net/analyse
2. Click on + to add new blueprint
3. Try to use random ship, or provide a steam workshop url or id
4. Observe: 
    Chrome: Error: Failed to fetch
    Edge: Error: Failed to fetch
    Firefox: Error: NetworkError when attempting to fetch resource.

### Expected behavior
Site loads blueprint from steam workshop

### Screenshots
Not really needed, I think

### Your Device (please complete the following information):
- OS: Windows 10, build 2004
- Browser:
        Chrome: Version 83.0.4103.106 (Official Build) (64-bit)
        FF: 77.0.1 (64-bit)
        Edge: 44.19041.1.0 (Non-chromium version)

Also on Android phone Chrome v. 83.0.4102.106, and other friends across the country have tried on theirs and get same issue so not my own internet

### Additional context
Have tried this with:

https://steamcommunity.com/sharedfiles/filedetails/?id=1913870563
https://spaceengineerspraisal.net/analyse?steam=1913870563
https://steamcommunity.com/workshop/filedetails/?id=1941969822
https://spaceengineerspraisal.net/analyse?steam=1941969822
https://steamcommunity.com/sharedfiles/filedetails/?id=2111026613 (which has worked before)
https://spaceengineerspraisal.net/analyse?steam=2111026613

As well as the 'Analyse Random' button, in Chrome, Firefox, and Edge. I can browse to the workshop pages in the same browser window just fine. I have also tried ensuring I'm logged into workshop in the same browser window, and without logging in, both give the same message.

Verified not my own internet by having friends test from different locations in the US.

Different message in FF than in Chrome/IE suggests javascript error.

**Comment by Akuukis** [comment]
Thank you, server restarted and that fixed the problem. For now I will setup a simple regular restart and uptime watcher, let's see if that's enough.
