### ISSUE TITLE
Cannot get the site to search BPs, Only gives "Error, Retry?" 

### ISSUE THREAD

**Issue by MdBourg98** [Akuukis/sepraisal#42]
### Summary
Cannot get the site to search BPs, Only gives "Error, Retry?" 

### Steps to Reproduce actual behavior

1. Go To- https://spaceengineerspraisal.net/browse
2. Wait, OR Search anything, OR Change settings
3. "Error, Retry?"

### Expected behavior
Showing Blueprints.

### Screenshots
https://imgur.com/a/0KRBXdp

### Your Device (please complete the following information):
- OS: Windows 10
- Browser: Firefox
- Version: 93.0 (64-bit)

### Additional context
Search was working 2 hours ago. Cleared cookies and other site data, still not working.

**Comment by Akuukis** [comment]
Thanks! The same happens for me.

Also uptime service reported API servers to be down between 20:05 and 20:09 (half hour ago). Seems weird that API isn't operational so long after the restart..
